<a href="https://colab.research.google.com/github/AshwinUnnikrishnan/AI-for-Human-Computer-Interaction/blob/main/Assignment1/HCI_AI_First_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[link text](https://)

# 1st Homework Assignment in Human A.I.

This assignment will ramp you up on being able to process large scale data sets and use them for Human A.I. interaction. We will work in particular with the dataset of full_home_loans.csv which is about home loan applications in Washington state, USA, where each row of the dataset is an individual loan application.

**Goal.** Your goal in this assignment is to build a machine learning model that can accurately predict whether a given loan application was accepted or rejected. In order to accomplish this you will learn skills to: (1)  process large scale data; (2) preparing the data for the machine learning models; (3) developing machine learning models.(4) creating your own machine learning datasets.


**Part 1: Data Exploration**
The first few exercises will get you used to looking at the data using pandas. Pandas is a widely used library in python for manipulating data. Why? Datasets can consume a lot of space in your computer's memory and traditional python data structures like lists or dictionaries will become painfully slow as we add thousands of rows of data. We use a specialized dataset library pandas which has a specialized data structure called a dataframe designed to be ultra fast & efficient. Documentation is here: https://pandas.pydata.org/pandas-docs/stable/

In [1]:

from google.colab import files
from __future__ import print_function
import io
import pandas as pd
import numpy as np


#Code to upload the dataset from your computer as a dataframe
#uploaded = files.upload()
nameFile="home_loans.csv"
df = pd.read_csv(nameFile)

<ipython-input-1-23645a6623d7>:11: DtypeWarning: Columns (10,11,12,14,15,16,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(nameFile)

# `Processing Data Using Pandas`

To understand what kind of data was collected, pandas has some handy commands:

* **df.head()** will show us the first 5 rows of our dataset. You can
also specify the first N rows, like df.head(18) will show us the first 18 rows.
* **df.sample(10)** will show us 10 randomly sampled rows of our dataset
* **df.shape** will tell us how many rows and how many columns are in the dataset
* **df.columns** will list the names of all columns in the dataset
* **df.describe()** will give you summary statistics about all numerical columns in the dataset


## Question 1.A: How many rows are in this dataset? How many columns?

 Show your work in code below if applicable.

In [2]:
# df.shape print the rows, columns
row, col = df.shape
print(f"Number of rows = {row} and Number of cols = {col}")

Number of rows = 369281 and Number of cols = 27

## Question 1.B: One of the columns in the dataset is the outcome value for each application, the value we will try to predict. Which column is that?

In [3]:
print("loan_approved is the column to be predicted")
print(df['loan_approved'].unique())
print(len(df[df['loan_approved'] == 0]))
print(len(df[df['loan_approved'] == 1]))

loan_approved is the column to be predicted
[1 0]
60380
308901

In [4]:
#Add your response and code here:
for k in df.keys():
  print(k)
#df.head(5)

town_name
county_name
loan_amount_000s
applicant_income_000s
property_type_name
occupied_by_owner
loan_type_name
is_hoepa_loan
loan_purpose_name
loan_approved
denial_reason_name_3
denial_reason_name_2
denial_reason_name_1
co_applicant_sex_name
co_applicant_race_name_5
co_applicant_race_name_4
co_applicant_race_name_3
co_applicant_race_name_2
co_applicant_race_name_1
co_applicant_ethnicity_name
applicant_sex_name
applicant_race_name_5
applicant_race_name_4
applicant_race_name_3
applicant_race_name_2
applicant_race_name_1
applicant_ethnicity_name

## Question 1.C: What reasons were given in this dataset for denying a loan application?

Hint: There are 3 columns in the dataset that list why a loan was denied. Try looking up the pandas command to list the unique values in a column.

Show your work in code below if applicable.

In [5]:
#Add your response and code here:

def get_denial_reason_unique(daf, col):
  print(f"-------------------{col}----------------------")
  reasons = []
  for val in daf[col].unique():
    if not pd.isna(val):
      reasons.append(val)
      print(val)
  return reasons

reasons_3 = get_denial_reason_unique(df, 'denial_reason_name_3')
reasons_2 = get_denial_reason_unique(df, 'denial_reason_name_2')
reasons_1 = get_denial_reason_unique(df, 'denial_reason_name_1')
combined_reasons = reasons_3 + reasons_1 + reasons_2

-------------------denial_reason_name_3----------------------
Other
Credit history
Insufficient cash (downpayment, closing costs)
Employment history
Debt-to-income ratio
Unverifiable information
Collateral
Credit application incomplete
Mortgage insurance denied
-------------------denial_reason_name_2----------------------
Collateral
Other
Insufficient cash (downpayment, closing costs)
Debt-to-income ratio
Employment history
Credit application incomplete
Credit history
Unverifiable information
Mortgage insurance denied
-------------------denial_reason_name_1----------------------
Other
Credit application incomplete
Collateral
Debt-to-income ratio
Credit history
Unverifiable information
Employment history
Insufficient cash (downpayment, closing costs)
Mortgage insurance denied

## Question 1.D: Given the denial reasons and the columns in this dataset, think about what information you don't have about each application. Rank your top 3 missing pieces of information about each application that could help you better predict the application's loan outcome.

Show your work in code below if applicable.



1.   Credit History
2.   Credit application incomplete
3.   Employment History


as seen in below eda we see that 8531 applications are rejected due to credit history, 6017 for application incomplete and 825 for employment history missing.

1951 applications are rejected due to unverifiable information, we do not know what that is specifically here.

In [6]:

def get_denial_reason_unique(df_d, column_name):
    df_d = df_d[df_d['loan_approved'] == 0]
    return df_d[column_name].value_counts()

def get_combined_counts_denial(df_d):
  # Get unique denial reasons and counts from each column
  reasons_1 = get_denial_reason_unique(df_d, 'denial_reason_name_1')
  reasons_2 = get_denial_reason_unique(df_d, 'denial_reason_name_2')
  reasons_3 = get_denial_reason_unique(df_d, 'denial_reason_name_3')
  # Combine the counts from the three columns
  combined_counts = reasons_1.add(reasons_2, fill_value=0).add(reasons_3, fill_value=0)

  # Print the combined counts
  print(combined_counts.sort_values(ascending=False))
get_combined_counts_denial(df)

Debt-to-income ratio                              9365
Credit history                                    8531
Credit application incomplete                     6017
Collateral                                        5783
Other                                             5314
Unverifiable information                          1951
Insufficient cash (downpayment, closing costs)    1894
Employment history                                 825
Mortgage insurance denied                           47
dtype: int64

# **Part 2: Preparing Data to Input to a Model**

Here we'll start using scikit-learn which provides simple library calls for most things we'd like to do in a simple machine learning pipeline. If you haven't used scikit-learn before this tutorial may be useful to give you a sense of what the library can do: https://scikit-learn.org/stable/tutorial/basic/tutorial.html

Machine learning models can only understand data that is represented numerically, but lots of the columns in our dataset like "town_name" are text categorical data. Meanwhile, many models do better when continous numerical data is within small, consistent ranges, such as all data being between -1, 0 and 1, which is definitely not the case with our thousands of dollars loan units.

So first, we will seperate out our samples (called X) into features we'd like to include in our model that are categorical or continous so that we can preprocess each appropriately seperately.

In [7]:
import sklearn # import scikit-learn
from sklearn import preprocessing # import preprocessing utilites

features_cat = ['loan_purpose_name', 'applicant_sex_name']
features_num = ['loan_amount_000s', 'applicant_income_000s']

X_cat = df[features_cat]
print (X_cat)
X_num = df[features_num]
print (X_num)

       loan_purpose_name applicant_sex_name
0            Refinancing             Female
1          Home purchase               Male
2            Refinancing               Male
3            Refinancing               Male
4       Home improvement             Female
...                  ...                ...
369276     Home purchase             Female
369277     Home purchase               Male
369278     Home purchase             Female
369279     Home purchase               Male
369280     Home purchase               Male

[369281 rows x 2 columns]
        loan_amount_000s  applicant_income_000s
0                    227                  116.0
1                    240                   42.0
2                    241                  117.0
3                    351                  315.0
4                    417                  114.0
...                  ...                    ...
369276               178                   97.0
369277               110                   30.0
369278               420                   71.0
369279               255                   77.0
369280               319                   78.0

[369281 rows x 2 columns]

**Part 2.A One Hot Encode Categorical Variables**

Run the following code to one hot encode the categorical features:

In [8]:
enc = preprocessing.OneHotEncoder()
enc.fit(X_cat) # fit the encoder to categories in our data
one_hot = enc.transform(X_cat) # transform data into one hot encoded sparse array format

In [9]:
# Finally, put the newly encoded sparse array back into a pandas dataframe so that we can use it
X_cat_proc = pd.DataFrame(one_hot.toarray(), columns=enc.get_feature_names_out())
X_cat_proc.head()

,loan_purpose_name_Home improvement,loan_purpose_name_Home purchase,loan_purpose_name_Refinancing,applicant_sex_name_Female,"applicant_sex_name_Information not provided by applicant in mail, Internet, or telephone application",applicant_sex_name_Male,applicant_sex_name_Not applicable
0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0

##Question 2.A: In your own words, how is one hot coding tranforming the categorical data? What does the term "one-hot" refer to?

---
The term "one-hot" in one-hot encoding refers to the way categorical data is represented after the encoding process.

In a one-hot encoded representation, each category or label in a categorical variable is uniquely assigned a binary vector (a sequence of 0s and 1s).

One means there is only one vector and hot is to refer which label is active.

If we have a feature as day of the week, in order to vectorize we can move it to a fixed length vector of 7, as there are only 7 values it can take 'xxxxxxx'.
then

- SUNDAY = 1000000
- MONDAY = 0100000
- .
- .
- .
- .
- SATURDAY = 0000001
---

## Part 2.B Scaling down continuous numerical data
Run the following code to normalize any continous numberical features, such as loan dollar amount, between -1 and 0. This process will ensure that the average of that feature, such as the average amount that a person asks for in loan amount, is scaled to 0. Values less than the average will be negative numbers, and values larger than the average will be positive numbers.

In [10]:
scaled = preprocessing.scale(X_num)
X_num_proc = pd.DataFrame(scaled, columns=features_num)
X_num_proc.head()

   loan_amount_000s  applicant_income_000s
0         -0.130864               0.016448
1         -0.103680              -0.596232
2         -0.101589               0.024727
3          0.128424               1.664059
4          0.266432              -0.000111

## Part 2.C Merge our feature sets into one sample dataset X and fix NaN values
Run the code below to combine the numerical and categorical feature sets.

In [11]:
X = pd.concat([X_num_proc, X_cat_proc], axis=1, sort=False)
X.head()

,loan_amount_000s,applicant_income_000s,loan_purpose_name_Home improvement,loan_purpose_name_Home purchase,loan_purpose_name_Refinancing,applicant_sex_name_Female,"applicant_sex_name_Information not provided by applicant in mail, Internet, or telephone application",applicant_sex_name_Male,applicant_sex_name_Not applicable
0,-0.130864,0.016448,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,-0.103680,-0.596232,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,-0.101589,0.024727,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.128424,1.664059,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.266432,-0.000111,1.0,0.0,0.0,1.0,0.0,0.0,0.0

## Question 2.C The code line below removes any NaN values in our sample with 0. NaNs are missing values that a model won't be able to understand. What is the semantic meaning of replaceing a NaN with 0 for the categorical variables? And for the continous numerical variables?

---
NaN is normally used when the data is missing or undefined.

**Categorical Variables**
- When we replace NaNs with 0, we are creating a new label or value in that category that means nothing.
- Example : if we have 0 instead of a string or vector representing a color or a day of week, or phone type it leads us to understanding that there is no color, no day, no phone number respectively, leading to misintrepretation.

**Continuous Numerical Variables**
- When we are assigning a 0 to NaN, it means that the value associated to that particular row is 0.
- Imagine we have NaN for height, income or loan amount instead of putting missing value if we put 0, it tends to mean 0 height, 0 income and 0 loan, which is wrong.

Hence we should come up with other special characters for NaNs.

---

In [12]:
X = X.fillna(0) # remove NaN values

## Part 2.D Create our target array y that our model will try to predict

In [13]:
y = df['loan_approved'] # target

In [14]:
y.unique()

array([1, 0])

## Part 2.E Split our data into training, test, and validation sets
Run the code below to split the data. Both validation and test sets will be used for testing our model, but use the validation set while you are developing and improving your model, and leave the test for late stage evaluation.

In [15]:
y.shape

(369281,)

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_TEMP, y_train, y_TEMP = train_test_split(X, y, test_size=0.30) # split out into training 70% of our data
X_validation, X_test, y_validation, y_test = train_test_split(X_TEMP, y_TEMP, test_size=0.50) # split out into validation 15% of our data and test 15% of our data
print(X_train.shape, X_validation.shape, X_test.shape) # print data shape to check the sizing is correct

(258496, 9) (55392, 9) (55393, 9)

## Question 2.E: In a single sentence, what is the difference between train, test, and validation sets?
Post your response below.

In [17]:
'''
The train set is used to train a machine learning model on seen data, the validation set is used for model fine-tuning on unseen data during training, and the test set is
used to evaluate the model's performance on a separate set of unseen data, which it hasn't been trained on.
'''

"\nThe train set is used to train a machine learning model on seen data, the validation set is used for model fine-tuning on unseen data during training, and the test set is\nused to evaluate the model's performance on a separate set of unseen data, which it hasn't been trained on.\n"

# Part 3. Developing Models
Scikit-learn has a substantial library of different models we can use for classification. Below are implemented two of the most simple classification models, Logistic Regression and Dummy Classifier.

In [18]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# helper method to print basic model metrics
def metrics(y_true, y_pred):
    print('Confusion matrix:\n', confusion_matrix(y_true, y_pred))
    print('\nReport:\n', classification_report(y_true, y_pred))

In [19]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs').fit(X_train, y_train) # first fit (train) the model
y_pred = model.predict(X_validation) # next get the model's predictions for a sample in the validation set
metrics(y_validation, y_pred) # finally evaluate performance

Confusion matrix:
 [[    0  9143]
 [    0 46249]]

Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00      9143
           1       0.83      1.00      0.91     46249

    accuracy                           0.83     55392
   macro avg       0.42      0.50      0.46     55392
weighted avg       0.70      0.83      0.76     55392

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

The Dummy Classifier is a 'dummy' because it is going to use zero machine learning, and simply predict "approve this loan" (value 1) for every loan it sees.

In [20]:
from sklearn.dummy import DummyClassifier

approve_everyone = DummyClassifier(strategy='constant', constant = 1).fit(X_train, y_train) # first fit (train) the model
y_pred_dummy = approve_everyone.predict(X_validation) # next get the model's predictions for a sample in the validation set
metrics(y_validation, y_pred_dummy) # finally evaluate performance

Confusion matrix:
 [[    0  9143]
 [    0 46249]]

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00      9143
           1       0.83      1.00      0.91     46249

    accuracy                           0.83     55392
   macro avg       0.42      0.50      0.46     55392
weighted avg       0.70      0.83      0.76     55392

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## Question 3.A: Considering only the data itself, why do Logistic Regression and the Dummy Classifier perform the same? What is the semantic meaning for why Dummy Classifier has such high accuracy?
Show your work below.

---


- Logistic Regression : The model predicts everything to be in label 1 (loan approved), as we see from the confusion matrix there isnt a single case where the model predicts 0 as the outcome.

- Dummy classifier, always predicts as 1 and there is only one label (1) that is present in the entire dataset.


- Logistitc regression and dummy classifier perform same way because both of them predict 1 as the output no matter what the input is.

- Dummy Classifier has such high accuracy because of class imbalance, we see that there are 8938 (loan_approved = 0[19%]) and 46454 (load_approved = 1 [81%])
---

# **Part 4: Your turn!**

## Task 4.A: Create a new balanced dataset where exactly half of the samples are rejected loan applications and half are accepted loan application.

show your work below

### EDA

In [21]:
def count_each_label(combined_data_dup):
  print(f"Threshold = {int(combined_data_dup.shape[0]/2)}")
  approved = len(combined_data_dup[combined_data_dup['loan_approved'] == 1])
  not_approved = len(combined_data_dup[combined_data_dup['loan_approved'] == 0])
  print('--------------------------------------')
  print(f"Loan Approved Count = {approved}")
  print(f"Loan Not Approved Count = {not_approved}")
  print(f"Current Different = {abs(approved-not_approved)}")
  print("reduce approved") if approved > not_approved else print('reduce not approved')
  print('--------------------------------------')
  get_combined_counts_denial(combined_data_dup)

In [22]:
selected_columns = ['loan_amount_000s', 'applicant_income_000s',
       'occupied_by_owner', 'loan_type_name',
       'is_hoepa_loan', 'loan_purpose_name', 'loan_approved',
       'denial_reason_name_3', 'denial_reason_name_2', 'denial_reason_name_1','applicant_sex_name']

# Create a new DataFrame with the selected columns
new_df = df[selected_columns].copy()

In [23]:
count_each_label(new_df)

Threshold = 184640
--------------------------------------
Loan Approved Count = 308901
Loan Not Approved Count = 60380
Current Different = 248521
reduce approved
--------------------------------------
Debt-to-income ratio                              9365
Credit history                                    8531
Credit application incomplete                     6017
Collateral                                        5783
Other                                             5314
Unverifiable information                          1951
Insufficient cash (downpayment, closing costs)    1894
Employment history                                 825
Mortgage insurance denied                           47
dtype: int64

### 1.Denying loans for people who have income less than the loan amount

##### Denying for everyone who has loan_amount > income

In [24]:
new_df.loc[new_df[new_df['applicant_income_000s'] < new_df['loan_amount_000s']].index, 'loan_approved'] = 0

In [25]:
count_each_label(new_df)

Threshold = 184640
--------------------------------------
Loan Approved Count = 64176
Loan Not Approved Count = 305105
Current Different = 240929
reduce not approved
--------------------------------------
Debt-to-income ratio                              9365
Credit history                                    8531
Credit application incomplete                     6017
Collateral                                        5783
Other                                             5314
Unverifiable information                          1951
Insufficient cash (downpayment, closing costs)    1894
Employment history                                 825
Mortgage insurance denied                           47
dtype: int64

In [26]:
# Checking if all approved loans have any reason of denial to clean it
len(new_df[
    (new_df['denial_reason_name_1'].isna() & new_df['denial_reason_name_2'].isna()) &
    (new_df['denial_reason_name_3'].isna()) & new_df['loan_approved'] == 1])

64176

### 2.Check for Wrong loan denial

In [27]:
approved_loans_2 = new_df[new_df['loan_approved'] == 1]
rejected_loans_2 = new_df[new_df['loan_approved'] == 0]

When the loan amount is less than income and thats the only rejection reason.

In [28]:
rejected_loans_ratio_denied = rejected_loans_2[
    ((rejected_loans_2['denial_reason_name_1'] == 'Debt-to-income ratio') |
     (rejected_loans_2['denial_reason_name_2'] == 'Debt-to-income ratio') |
     (rejected_loans_2['denial_reason_name_3'] == 'Debt-to-income ratio'))
]

rejected_only_money = rejected_loans_ratio_denied[
    (rejected_loans_ratio_denied['denial_reason_name_1'].isna() & rejected_loans_ratio_denied['denial_reason_name_2'].isna()) |
    (rejected_loans_ratio_denied['denial_reason_name_1'].isna() & rejected_loans_ratio_denied['denial_reason_name_3'].isna()) |
    (rejected_loans_ratio_denied['denial_reason_name_2'].isna() & rejected_loans_ratio_denied['denial_reason_name_3'].isna())
]

People who got rejected for loan to income ratio but have more income than loan

In [29]:
len(rejected_only_money[(rejected_only_money['applicant_income_000s'] ) >= rejected_only_money['loan_amount_000s']])

375

Finding number of people who have loan amount just more than 1.1*income or income more than loan

In [30]:
len(rejected_only_money[(rejected_only_money['applicant_income_000s'] + 0.2*(rejected_only_money['applicant_income_000s'])) >= rejected_only_money['loan_amount_000s']])

436

In [31]:
new_df_loan_approved = new_df.copy()
new_df_loan_approved.loc[rejected_only_money[(rejected_only_money['applicant_income_000s'] + 0.2*(rejected_only_money['applicant_income_000s'])) > rejected_only_money['loan_amount_000s']].index, 'loan_approved'] = 1
rejected_only_money.loc[rejected_only_money[(rejected_only_money['applicant_income_000s'] + 0.2*(rejected_only_money['applicant_income_000s'])) > rejected_only_money['loan_amount_000s']].index, 'loan_approved'] = 1
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 64611
Loan Not Approved Count = 304670
Current Different = 240059
reduce not approved
--------------------------------------
Debt-to-income ratio                              8930
Credit history                                    8531
Credit application incomplete                     6017
Collateral                                        5783
Other                                             5314
Unverifiable information                          1951
Insufficient cash (downpayment, closing costs)    1894
Employment history                                 825
Mortgage insurance denied                           47
dtype: int64

In [32]:
rejected_only_money = rejected_only_money[rejected_only_money['loan_approved'] == 0]

### 3.EDA on rejection only money approving when guaranteed

In [33]:
len(rejected_only_money)

5336

In [34]:
new_df_loan_approved.iloc[265765]

loan_amount_000s                           45
applicant_income_000s                    35.0
occupied_by_owner                           1
loan_type_name                   Conventional
is_hoepa_loan                               0
loan_purpose_name            Home improvement
loan_approved                               0
denial_reason_name_3                      NaN
denial_reason_name_2                      NaN
denial_reason_name_1     Debt-to-income ratio
applicant_sex_name                       Male
Name: 265765, dtype: object

In [35]:
def get_difference(df_d):
  return df_d['loan_amount_000s'] - df_d['applicant_income_000s']

In [36]:
get_difference(rejected_only_money).nsmallest(10)

294574    1.0
281505    5.0
316941    5.0
295606    7.0
307592    7.0
320355    7.0
304620    8.0
279851    9.0
315803    9.0
319936    9.0
dtype: float64

Get rejected based on just income and check the loan_type_name

In [37]:
loan_type_counts = rejected_only_money['loan_type_name'].value_counts()

# Print the counts
print(loan_type_counts)

Conventional          4348
FHA-insured            554
VA-guaranteed          371
FSA/RHS-guaranteed      63
Name: loan_type_name, dtype: int64

Approving loans where only loan:income is problem and is guaranteed FHA, VA, FSA/RHS

In [38]:
rejected_only_money_guaranteed = rejected_only_money[rejected_only_money['loan_type_name'] != 'Conventional']
rejected_only_money_guaranteed['loan_approved'] = 1

<ipython-input-38-83b5ee945d2f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rejected_only_money_guaranteed['loan_approved'] = 1

In [39]:
new_df_loan_approved.loc[rejected_only_money_guaranteed.index, 'loan_approved'] = 1

In [40]:
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 65599
Loan Not Approved Count = 303682
Current Different = 238083
reduce not approved
--------------------------------------
Credit history                                    8531
Debt-to-income ratio                              7942
Credit application incomplete                     6017
Collateral                                        5783
Other                                             5314
Unverifiable information                          1951
Insufficient cash (downpayment, closing costs)    1894
Employment history                                 825
Mortgage insurance denied                           47
dtype: int64

### 4.Credit History only issue with someone guaranteed approving those

In [41]:
rejected_loans_3 = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]

In [42]:
rejected_loans_creditHistory = rejected_loans_3[
    ((rejected_loans_3['denial_reason_name_1'] == 'Credit history') |
     (rejected_loans_3['denial_reason_name_2'] == 'Credit history') |
     (rejected_loans_3['denial_reason_name_3'] == 'Credit history'))
]

rejected_only_credit = rejected_loans_creditHistory[
    ((rejected_loans_creditHistory['denial_reason_name_1'].isna() & rejected_loans_creditHistory['denial_reason_name_2'].isna()) |
    (rejected_loans_creditHistory['denial_reason_name_1'].isna() & rejected_loans_creditHistory['denial_reason_name_3'].isna()) |
    (rejected_loans_creditHistory['denial_reason_name_2'].isna() & rejected_loans_creditHistory['denial_reason_name_3'].isna())) &
    (rejected_loans_creditHistory['loan_type_name'] != 'Conventional')
]

In [43]:
rejected_only_credit

,loan_amount_000s,applicant_income_000s,occupied_by_owner,loan_type_name,is_hoepa_loan,loan_purpose_name,loan_approved,denial_reason_name_3,denial_reason_name_2,denial_reason_name_1,applicant_sex_name
246363,186,62.0,1,FHA-insured,0,Refinancing,0,NaN,NaN,Credit history,Male
246418,200,79.0,1,VA-guaranteed,0,Home purchase,0,NaN,NaN,Credit history,Female
246679,199,70.0,1,FHA-insured,0,Refinancing,0,NaN,NaN,Credit history,Male
246847,228,NaN,1,VA-guaranteed,0,Refinancing,0,NaN,NaN,Credit history,Male
247303,186,52.0,1,VA-guaranteed,0,Refinancing,0,NaN,NaN,Credit history,Male
...,...,...,...,...,...,...,...,...,...,...,...
322690,225,86.0,1,VA-guaranteed,0,Refinancing,0,NaN,NaN,Credit history,Male
322698,255,97.0,1,VA-guaranteed,0,Refinancing,0,NaN,NaN,Credit history,Male
322702,261,65.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Credit history,Male
322795,300,51.0,1,VA-guaranteed,0,Home purchase,0,NaN,NaN,Credit history,Female
322796,204,45.0,1,FHA-insured,0,Refinancing,0,NaN,NaN,Credit history,Female

In [44]:
new_df_loan_approved.loc[rejected_only_credit.index, 'loan_approved'] = 1

In [45]:
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 67236
Loan Not Approved Count = 302045
Current Different = 234809
reduce not approved
--------------------------------------
Debt-to-income ratio                              7942
Credit history                                    6894
Credit application incomplete                     6017
Collateral                                        5783
Other                                             5314
Unverifiable information                          1951
Insufficient cash (downpayment, closing costs)    1894
Employment history                                 825
Mortgage insurance denied                           47
dtype: int64

### 5. Employment History and guaranteed by someone

In [46]:
rejected_loans_3 = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]

In [47]:
rejected_loans_creditHistory = rejected_loans_3[
    ((rejected_loans_3['denial_reason_name_1'] == 'Employment history') |
     (rejected_loans_3['denial_reason_name_2'] == 'Employment history') |
     (rejected_loans_3['denial_reason_name_3'] == 'Employment history'))
]

rejected_only_employment = rejected_loans_creditHistory[
    ((rejected_loans_creditHistory['denial_reason_name_1'].isna() & rejected_loans_creditHistory['denial_reason_name_2'].isna()) |
    (rejected_loans_creditHistory['denial_reason_name_1'].isna() & rejected_loans_creditHistory['denial_reason_name_3'].isna()) |
    (rejected_loans_creditHistory['denial_reason_name_2'].isna() & rejected_loans_creditHistory['denial_reason_name_3'].isna())) &
    (rejected_loans_creditHistory['loan_type_name'] != 'Conventional')
]

In [48]:
rejected_only_employment

,loan_amount_000s,applicant_income_000s,occupied_by_owner,loan_type_name,is_hoepa_loan,loan_purpose_name,loan_approved,denial_reason_name_3,denial_reason_name_2,denial_reason_name_1,applicant_sex_name
248346,85,39.0,1,FHA-insured,0,Refinancing,0,NaN,NaN,Employment history,Male
248798,92,48.0,1,FHA-insured,0,Refinancing,0,NaN,NaN,Employment history,Female
249781,145,34.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Employment history,Female
249852,150,34.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Employment history,Female
254145,238,64.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Employment history,Male
...,...,...,...,...,...,...,...,...,...,...,...
320203,143,33.0,1,FSA/RHS-guaranteed,0,Home purchase,0,NaN,NaN,Employment history,Female
320246,143,45.0,1,FHA-insured,0,Refinancing,0,NaN,NaN,Employment history,Male
320787,155,60.0,1,VA-guaranteed,0,Refinancing,0,NaN,NaN,Employment history,Male
322011,276,109.0,1,FHA-insured,0,Home purchase,0,Employment history,NaN,NaN,Female
322014,147,34.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Employment history,Female

In [49]:
new_df_loan_approved.loc[rejected_only_employment.index, 'loan_approved'] = 1

In [50]:
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 67350
Loan Not Approved Count = 301931
Current Different = 234581
reduce not approved
--------------------------------------
Debt-to-income ratio                              7942
Credit history                                    6894
Credit application incomplete                     6017
Collateral                                        5783
Other                                             5314
Unverifiable information                          1951
Insufficient cash (downpayment, closing costs)    1894
Employment history                                 711
Mortgage insurance denied                           47
dtype: int64

### 6. No Reason loan rejected with guaranteed ( Approving them as well )

In [51]:
rejected_loan = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]

In [52]:
rejected_loan

,loan_amount_000s,applicant_income_000s,occupied_by_owner,loan_type_name,is_hoepa_loan,loan_purpose_name,loan_approved,denial_reason_name_3,denial_reason_name_2,denial_reason_name_1,applicant_sex_name
0,227,116.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Female
1,240,42.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,NaN,Male
2,241,117.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Male
3,351,315.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Male
4,417,114.0,1,Conventional,0,Home improvement,0,NaN,NaN,NaN,Female
...,...,...,...,...,...,...,...,...,...,...,...
369276,178,97.0,1,FHA-insured,0,Home purchase,0,NaN,Collateral,Credit application incomplete,Female
369277,110,30.0,1,FSA/RHS-guaranteed,0,Home purchase,0,NaN,Collateral,Credit history,Male
369278,420,71.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Female
369279,255,77.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,NaN,Male
369280,319,78.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Male

In [53]:
rejected_only_no_reason = rejected_loan[
    (rejected_loan['denial_reason_name_1'].isna() &
      rejected_loan['denial_reason_name_2'].isna() &
      rejected_loan['denial_reason_name_3'].isna())]

In [54]:
rejected_only_no_reason_guaranteed = rejected_only_no_reason[rejected_only_no_reason['loan_type_name'] != 'Conventional']

In [55]:
new_df_loan_approved.loc[rejected_only_no_reason_guaranteed.index, 'loan_approved'] = 1

In [56]:
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 131103
Loan Not Approved Count = 238178
Current Different = 107075
reduce not approved
--------------------------------------
Debt-to-income ratio                              7942
Credit history                                    6894
Credit application incomplete                     6017
Collateral                                        5783
Other                                             5314
Unverifiable information                          1951
Insufficient cash (downpayment, closing costs)    1894
Employment history                                 711
Mortgage insurance denied                           47
dtype: int64

### 7. Home loans where collateral is the only issue and is guaranteed are approved

In [57]:
rejected_loan = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]
rejected_loan_guaranteed = rejected_loan[rejected_loan['loan_type_name'] != 'Conventional']

In [58]:
rejected_only_one_reason = rejected_loan_guaranteed[
    ( rejected_loan_guaranteed['denial_reason_name_2'].isna() &
      rejected_loan_guaranteed['denial_reason_name_3'].isna())]

In [59]:
rejected_only_no_reason['denial_reason_name_1'].unique()

array([nan], dtype=object)

In [60]:
rejected_only_no_reason['loan_purpose_name'].unique()

array(['Refinancing', 'Home purchase', 'Home improvement'], dtype=object)

In [61]:
rejected_only_one_reason[rejected_only_one_reason['loan_purpose_name'] != 'Refinancing']

,loan_amount_000s,applicant_income_000s,occupied_by_owner,loan_type_name,is_hoepa_loan,loan_purpose_name,loan_approved,denial_reason_name_3,denial_reason_name_2,denial_reason_name_1,applicant_sex_name
246179,376,160.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Credit application incomplete,Male
246188,320,60.0,1,VA-guaranteed,0,Home purchase,0,NaN,NaN,Credit application incomplete,Female
246543,85,43.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Other,Female
247799,217,69.0,1,FSA/RHS-guaranteed,0,Home purchase,0,NaN,NaN,Collateral,Male
248132,170,47.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Unverifiable information,Male
...,...,...,...,...,...,...,...,...,...,...,...
322608,215,116.0,1,VA-guaranteed,0,Home purchase,0,NaN,NaN,Collateral,Male
322639,115,39.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Credit application incomplete,Male
322648,270,75.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Collateral,Male
322651,489,93.0,1,VA-guaranteed,0,Home purchase,0,NaN,NaN,Credit application incomplete,Male
322814,222,40.0,1,FHA-insured,0,Home purchase,0,NaN,NaN,Collateral,Male

In [62]:
new_df_loan_approved.loc[rejected_only_one_reason.index, 'loan_approved'] = 1
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 134814
Loan Not Approved Count = 234467
Current Different = 99653
reduce not approved
--------------------------------------
Debt-to-income ratio                              7942
Credit history                                    6894
Collateral                                        4788
Credit application incomplete                     4484
Other                                             4479
Unverifiable information                          1750
Insufficient cash (downpayment, closing costs)    1748
Employment history                                 711
Mortgage insurance denied                           46
dtype: int64

### 8. Approving guaranteed where the reason is credit or employment or income ratio

In [63]:
rejected_loan = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]

In [64]:
rejected_loan

,loan_amount_000s,applicant_income_000s,occupied_by_owner,loan_type_name,is_hoepa_loan,loan_purpose_name,loan_approved,denial_reason_name_3,denial_reason_name_2,denial_reason_name_1,applicant_sex_name
0,227,116.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Female
2,241,117.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Male
3,351,315.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Male
4,417,114.0,1,Conventional,0,Home improvement,0,NaN,NaN,NaN,Female
9,199,37.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Male
...,...,...,...,...,...,...,...,...,...,...,...
369275,216,42.0,1,FHA-insured,0,Home purchase,0,NaN,Credit application incomplete,Employment history,Male
369276,178,97.0,1,FHA-insured,0,Home purchase,0,NaN,Collateral,Credit application incomplete,Female
369277,110,30.0,1,FSA/RHS-guaranteed,0,Home purchase,0,NaN,Collateral,Credit history,Male
369278,420,71.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Female
369280,319,78.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Male

In [65]:

# Create a new DataFrame with the selected columns
combinations_df = rejected_loan.copy()
combinations_df = combinations_df[combinations_df['denial_reason_name_2'] == 'Credit history']
# Use the drop_duplicates method to get unique combinations

In [66]:
desired_reasons = ['Credit history', 'Debt-to-income ratio', 'Employment history']
mask = ((combinations_df['denial_reason_name_3'].isin(desired_reasons) | combinations_df['denial_reason_name_3'].isna() )& \
      (combinations_df['denial_reason_name_2'].isin(desired_reasons) | combinations_df['denial_reason_name_2'].isna() )& \
      (combinations_df['denial_reason_name_1'].isin(desired_reasons) | combinations_df['denial_reason_name_1'].isna() ))

# Filter the DataFrame using the mask
filtered_combinations = combinations_df[mask]

# Display the rows with desired denial reasons
print(filtered_combinations)

        loan_amount_000s  applicant_income_000s  occupied_by_owner  \
248234               205                   72.0                  0
248808               275                   58.0                  1
248844               100                   12.0                  0
248971                71                   26.0                  1
250592               184                   87.0                  0
...                  ...                    ...                ...
322140                79                   44.0                  1
322355               179                   35.0                  1
322385               134                   58.0                  1
322422                15                   29.0                  0
322579               279                   98.0                  1

       loan_type_name  is_hoepa_loan loan_purpose_name  loan_approved  \
248234   Conventional              0       Refinancing              0
248808    FHA-insured              0       Refinancing              0
248844   Conventional              0     Home purchase              0
248971    FHA-insured              0       Refinancing              0
250592   Conventional              0     Home purchase              0
...               ...            ...               ...            ...
322140   Conventional              0       Refinancing              0
322355    FHA-insured              0     Home purchase              0
322385   Conventional              0       Refinancing              0
322422   Conventional              0  Home improvement              0
322579   Conventional              0     Home purchase              0

       denial_reason_name_3 denial_reason_name_2  denial_reason_name_1  \
248234                  NaN       Credit history  Debt-to-income ratio
248808                  NaN       Credit history  Debt-to-income ratio
248844                  NaN       Credit history  Debt-to-income ratio
248971                  NaN       Credit history  Debt-to-income ratio
250592                  NaN       Credit history  Debt-to-income ratio
...                     ...                  ...                   ...
322140                  NaN       Credit history  Debt-to-income ratio
322355                  NaN       Credit history  Debt-to-income ratio
322385                  NaN       Credit history  Debt-to-income ratio
322422                  NaN       Credit history  Debt-to-income ratio
322579                  NaN       Credit history  Debt-to-income ratio

                                       applicant_sex_name
248234                                               Male
248808                                               Male
248844                                               Male
248971                                             Female
250592                                             Female
...                                                   ...
322140                                               Male
322355                                             Female
322385                                             Female
322422                                               Male
322579  Information not provided by applicant in mail,...

[714 rows x 11 columns]

In [67]:
filtered_combinations = filtered_combinations[filtered_combinations['loan_type_name'] != 'Conventional']

In [68]:
new_df_loan_approved.loc[filtered_combinations.index, 'loan_approved'] = 1
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 134960
Loan Not Approved Count = 234321
Current Different = 99361
reduce not approved
--------------------------------------
Debt-to-income ratio                              7802
Credit history                                    6748
Collateral                                        4788
Credit application incomplete                     4484
Other                                             4479
Unverifiable information                          1750
Insufficient cash (downpayment, closing costs)    1748
Employment history                                 702
Mortgage insurance denied                           46
dtype: int64

### 9. Approving Conventional Loan where no reason given for cancellation and income*2 >= loan

In [69]:
rejected_loan = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]

In [70]:
rejected_loan

,loan_amount_000s,applicant_income_000s,occupied_by_owner,loan_type_name,is_hoepa_loan,loan_purpose_name,loan_approved,denial_reason_name_3,denial_reason_name_2,denial_reason_name_1,applicant_sex_name
0,227,116.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Female
2,241,117.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Male
3,351,315.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Male
4,417,114.0,1,Conventional,0,Home improvement,0,NaN,NaN,NaN,Female
9,199,37.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Male
...,...,...,...,...,...,...,...,...,...,...,...
369275,216,42.0,1,FHA-insured,0,Home purchase,0,NaN,Credit application incomplete,Employment history,Male
369276,178,97.0,1,FHA-insured,0,Home purchase,0,NaN,Collateral,Credit application incomplete,Female
369277,110,30.0,1,FSA/RHS-guaranteed,0,Home purchase,0,NaN,Collateral,Credit history,Male
369278,420,71.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Female
369280,319,78.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Male

In [71]:
rejected_no_reason = rejected_loan[
    ( rejected_loan['denial_reason_name_2'].isna() & rejected_loan['denial_reason_name_1'].isna() &
      rejected_loan['denial_reason_name_3'].isna())]

In [72]:
rejected_no_reason = rejected_no_reason[rejected_no_reason['applicant_income_000s']*2 > rejected_no_reason['loan_amount_000s']]

In [73]:
new_df_loan_approved.loc[rejected_no_reason.index, 'loan_approved'] = 1
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 181440
Loan Not Approved Count = 187841
Current Different = 6401
reduce not approved
--------------------------------------
Debt-to-income ratio                              7802
Credit history                                    6748
Collateral                                        4788
Credit application incomplete                     4484
Other                                             4479
Unverifiable information                          1750
Insufficient cash (downpayment, closing costs)    1748
Employment history                                 702
Mortgage insurance denied                           46
dtype: int64

### 10. Reason being employment history and Credit History and then income * 2> loan approving them

In [74]:
rejected_loan = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]

In [75]:
reason = ['Employment history', 'Credit history']
rejected_loans_ratio_denied = rejected_loan[
    ((rejected_loan['denial_reason_name_1'].isin(reason)) |
     (rejected_loan['denial_reason_name_2'].isin(reason)) |
     (rejected_loan['denial_reason_name_3'].isin(reason)))
]

rejected_only_money = rejected_loans_ratio_denied[
    (rejected_loans_ratio_denied['denial_reason_name_1'].isna() & rejected_loans_ratio_denied['denial_reason_name_2'].isna()) |
    (rejected_loans_ratio_denied['denial_reason_name_1'].isna() & rejected_loans_ratio_denied['denial_reason_name_3'].isna()) |
    (rejected_loans_ratio_denied['denial_reason_name_2'].isna() & rejected_loans_ratio_denied['denial_reason_name_3'].isna())
]

In [76]:
rejected_cred_emp_income_more = rejected_only_money[rejected_only_money['applicant_income_000s']*2 > rejected_only_money['loan_amount_000s']]

In [77]:
new_df_loan_approved.loc[rejected_cred_emp_income_more.index, 'loan_approved'] = 1
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 183195
Loan Not Approved Count = 186086
Current Different = 2891
reduce not approved
--------------------------------------
Debt-to-income ratio                              7802
Credit history                                    5038
Collateral                                        4788
Credit application incomplete                     4484
Other                                             4479
Unverifiable information                          1750
Insufficient cash (downpayment, closing costs)    1748
Employment history                                 657
Mortgage insurance denied                           46
dtype: int64

### 11. Merge with 10 .. collatral only reason and 2*salary more than loan

In [78]:
rejected_loan = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]

In [79]:
rejected_more_income = rejected_loan[2* rejected_loan['applicant_income_000s'] > rejected_loan['loan_amount_000s']]

In [80]:
reason = ['Collateral']
rejected_loans_ratio_denied = rejected_more_income[
    ((rejected_more_income['denial_reason_name_1'].isin(reason)) |
     (rejected_more_income['denial_reason_name_2'].isin(reason)) |
     (rejected_more_income['denial_reason_name_3'].isin(reason)))
]

rejected_only_money = rejected_loans_ratio_denied[
    (rejected_loans_ratio_denied['denial_reason_name_1'].isna() & rejected_loans_ratio_denied['denial_reason_name_2'].isna()) |
    (rejected_loans_ratio_denied['denial_reason_name_1'].isna() & rejected_loans_ratio_denied['denial_reason_name_3'].isna()) |
    (rejected_loans_ratio_denied['denial_reason_name_2'].isna() & rejected_loans_ratio_denied['denial_reason_name_3'].isna())
]

In [81]:
new_df_loan_approved.loc[rejected_only_money.index, 'loan_approved'] = 1
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 184349
Loan Not Approved Count = 184932
Current Different = 583
reduce not approved
--------------------------------------
Debt-to-income ratio                              7802
Credit history                                    5038
Credit application incomplete                     4484
Other                                             4479
Collateral                                        3634
Unverifiable information                          1750
Insufficient cash (downpayment, closing costs)    1748
Employment history                                 657
Mortgage insurance denied                           46
dtype: int64

### 12. Guaranteed loans where issue is collatral or history or income ratio approving

In [82]:
rejected_loan = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]

In [83]:
rejected_loan = rejected_loan[rejected_loan['loan_type_name'] != 'Conventional']

In [84]:
selected_columns = ['denial_reason_name_3', 'denial_reason_name_2', 'denial_reason_name_1']

# Create a new DataFrame with the selected columns
combinations_df = rejected_loan[selected_columns]

In [85]:
desired_reasons = ['Credit history', 'Employment history', 'Collateral','Debt-to-income ratio']
mask = ((combinations_df['denial_reason_name_3'].isin(desired_reasons) |
        combinations_df['denial_reason_name_3'].isna())
        &
       (combinations_df['denial_reason_name_1'].isin(desired_reasons) |
        combinations_df['denial_reason_name_1'].isna())
       &
        (combinations_df['denial_reason_name_2'].isin(desired_reasons) |
        combinations_df['denial_reason_name_2'].isna()))


# Filter the DataFrame using the mask
filtered_combinations = combinations_df[mask]

In [86]:
new_df_loan_approved.loc[filtered_combinations.index, 'loan_approved'] = 1
count_each_label(new_df_loan_approved)

Threshold = 184640
--------------------------------------
Loan Approved Count = 184578
Loan Not Approved Count = 184703
Current Different = 125
reduce not approved
--------------------------------------
Debt-to-income ratio                              7597
Credit history                                    4930
Credit application incomplete                     4484
Other                                             4479
Collateral                                        3577
Unverifiable information                          1750
Insufficient cash (downpayment, closing costs)    1748
Employment history                                 556
Mortgage insurance denied                           46
dtype: int64

### 13. Extra

In [87]:
rejected_loan = new_df_loan_approved[new_df_loan_approved['loan_approved'] == 0]

In [88]:
rejected_loan

,loan_amount_000s,applicant_income_000s,occupied_by_owner,loan_type_name,is_hoepa_loan,loan_purpose_name,loan_approved,denial_reason_name_3,denial_reason_name_2,denial_reason_name_1,applicant_sex_name
2,241,117.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Male
4,417,114.0,1,Conventional,0,Home improvement,0,NaN,NaN,NaN,Female
9,199,37.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Male
10,885,150.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Male
11,338,59.0,1,Conventional,0,Refinancing,0,NaN,NaN,NaN,Female
...,...,...,...,...,...,...,...,...,...,...,...
369274,209,41.0,1,Conventional,0,Home purchase,0,NaN,Credit application incomplete,Unverifiable information,Male
369275,216,42.0,1,FHA-insured,0,Home purchase,0,NaN,Credit application incomplete,Employment history,Male
369276,178,97.0,1,FHA-insured,0,Home purchase,0,NaN,Collateral,Credit application incomplete,Female
369278,420,71.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Female
369280,319,78.0,1,Conventional,0,Home purchase,0,NaN,NaN,NaN,Male


## Task 4.B: Below, retry training and evaluating a Logistic regression model on the updated data.
show your work below

In [89]:
new_df_loan_approved.keys()

Index(['loan_amount_000s', 'applicant_income_000s', 'occupied_by_owner',
       'loan_type_name', 'is_hoepa_loan', 'loan_purpose_name', 'loan_approved',
       'denial_reason_name_3', 'denial_reason_name_2', 'denial_reason_name_1',
       'applicant_sex_name'],
      dtype='object')

In [90]:
new_df_loan_approved.loc[new_df_loan_approved['loan_approved'] == 1, 'denial_reason_name_1'] = np.nan
new_df_loan_approved.loc[new_df_loan_approved['loan_approved'] == 1, 'denial_reason_name_2'] = np.nan
new_df_loan_approved.loc[new_df_loan_approved['loan_approved'] == 1, 'denial_reason_name_3'] = np.nan

In [91]:
#features_cat = ['loan_type_name', 'loan_purpose_name','denial_reason_name_3','denial_reason_name_2','denial_reason_name_1']

X_cat = new_df_loan_approved[features_cat]
X_num = new_df_loan_approved[features_num]

       loan_purpose_name applicant_sex_name
0            Refinancing             Female
1          Home purchase               Male
2            Refinancing               Male
3            Refinancing               Male
4       Home improvement             Female
...                  ...                ...
369276     Home purchase             Female
369277     Home purchase               Male
369278     Home purchase             Female
369279     Home purchase               Male
369280     Home purchase               Male

[369281 rows x 2 columns]
        loan_amount_000s  applicant_income_000s
0                    227                  116.0
1                    240                   42.0
2                    241                  117.0
3                    351                  315.0
4                    417                  114.0
...                  ...                    ...
369276               178                   97.0
369277               110                   30.0
369278               420                   71.0
369279               255                   77.0
369280               319                   78.0

[369281 rows x 2 columns]

In [99]:
def preprocessing_data_X_y(data, features_cat, features_num):

  X_cat = data[features_cat]
  X_num = data[features_num]
  enc = preprocessing.OneHotEncoder()
  enc.fit(X_cat) # fit the encoder to categories in our data
  one_hot = enc.transform(X_cat) # transform data into one hot encoded sparse array format
  # Finally, put the newly encoded sparse array back into a pandas dataframe so that we can use it
  X_cat_proc = pd.DataFrame(one_hot.toarray(), columns=enc.get_feature_names_out())
  X_cat_proc.head()
  scaled = preprocessing.scale(X_num)
  X_num_proc = pd.DataFrame(scaled, columns=features_num)
  X_num_proc.head()
  X = pd.concat([X_num_proc, X_cat_proc], axis=1, sort=False)
  X.head()
  X = X.fillna(0) # remove NaN values
  y = data['loan_approved'] # target
  return X, y

In [100]:
features_cat = ['loan_purpose_name', 'applicant_sex_name']
features_num = ['loan_amount_000s', 'applicant_income_000s']
X, y = preprocessing_data_X_y(new_df_loan_approved, features_cat, features_num)

In [101]:
from sklearn.model_selection import train_test_split
X_train, X_TEMP, y_train, y_TEMP = train_test_split(X, y, test_size=0.30) # split out into training 70% of our data
X_validation, X_test, y_validation, y_test = train_test_split(X_TEMP, y_TEMP, test_size=0.50) # split out into validation 15% of our data and test 15% of our data
print(X_train.shape, X_validation.shape, X_test.shape) # print data shape to check the sizing is correct

(258496, 9) (55392, 9) (55393, 9)

In [102]:
print(len(y_train[y_train == 1]))
print(len(y_train[y_train == 0]))
print(len(y_validation[y_validation == 1]))
print(len(y_validation[y_validation == 0]))
print(len(y_test[y_test == 1]))
print(len(y_test[y_test == 0]))

129380
129116
27673
27719
27525
27868

In [103]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs').fit(X_train, y_train) # first fit (train) the model
y_pred_validation = model.predict(X_validation) # next get the model's predictions for a sample in the validation set
metrics(y_validation, y_pred_validation) # finally evaluate performance
y_pred_test = model.predict(X_test) # next get the model's predictions for a sample in the validation set
metrics(y_test, y_pred_test) # finally evaluate performance

Confusion matrix:
 [[21903  5816]
 [ 9393 18280]]

Report:
               precision    recall  f1-score   support

           0       0.70      0.79      0.74     27719
           1       0.76      0.66      0.71     27673

    accuracy                           0.73     55392
   macro avg       0.73      0.73      0.72     55392
weighted avg       0.73      0.73      0.72     55392

Confusion matrix:
 [[21938  5930]
 [ 9212 18313]]

Report:
               precision    recall  f1-score   support

           0       0.70      0.79      0.74     27868
           1       0.76      0.67      0.71     27525

    accuracy                           0.73     55393
   macro avg       0.73      0.73      0.73     55393
weighted avg       0.73      0.73      0.73     55393

## Task 4.C: Use your own imagination and experimentation to improve predictive performance for this task, modifying the model choices, feature choices, and data processing however you wish.

Important! Your ability to improve the model above the baseline after Task 4.B will count for 10% of this assignment grade, with 5% of that given for modest improvements to performance. Thus while we encourage you to experiment, do not sink excessive time into this task. We will test the performance on our own holdout dataset.

show your work below

In [104]:
new_df_loan_approved.keys()

Index(['loan_amount_000s', 'applicant_income_000s', 'occupied_by_owner',
       'loan_type_name', 'is_hoepa_loan', 'loan_purpose_name', 'loan_approved',
       'denial_reason_name_3', 'denial_reason_name_2', 'denial_reason_name_1',
       'applicant_sex_name'],
      dtype='object')

### Approach 1 : Adding more features loan_type_name, loan_purpose, denial reasons (3), applicant_sex_name

In [105]:
features_cat = ['loan_purpose_name', 'applicant_sex_name', 'loan_type_name', 'loan_purpose_name', 'denial_reason_name_3','denial_reason_name_2','denial_reason_name_1']
features_num = ['loan_amount_000s', 'applicant_income_000s']
X, y = preprocessing_data_X_y(new_df_loan_approved, features_cat, features_num)

In [106]:
from sklearn.model_selection import train_test_split
X_train, X_TEMP, y_train, y_TEMP = train_test_split(X, y, test_size=0.30) # split out into training 70% of our data
X_validation, X_test, y_validation, y_test = train_test_split(X_TEMP, y_TEMP, test_size=0.50) # split out into validation 15% of our data and test 15% of our data
print(X_train.shape, X_validation.shape, X_test.shape) # print data shape to check the sizing is correct

(258496, 46) (55392, 46) (55393, 46)

In [107]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs').fit(X_train, y_train) # first fit (train) the model
y_pred_validation = model.predict(X_validation) # next get the model's predictions for a sample in the validation set
metrics(y_validation, y_pred_validation) # finally evaluate performance
y_pred_test = model.predict(X_test) # next get the model's predictions for a sample in the validation set
metrics(y_test, y_pred_test) # finally evaluate performance

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Confusion matrix:
 [[27033   522]
 [ 2211 25626]]

Report:
               precision    recall  f1-score   support

           0       0.92      0.98      0.95     27555
           1       0.98      0.92      0.95     27837

    accuracy                           0.95     55392
   macro avg       0.95      0.95      0.95     55392
weighted avg       0.95      0.95      0.95     55392

Confusion matrix:
 [[27199   509]
 [ 2203 25482]]

Report:
               precision    recall  f1-score   support

           0       0.93      0.98      0.95     27708
           1       0.98      0.92      0.95     27685

    accuracy                           0.95     55393
   macro avg       0.95      0.95      0.95     55393
weighted avg       0.95      0.95      0.95     55393

**Conclusion** : As we see from the data we see a 20% increase in accurace f1 score.

### Approach 2 : Attenmpting Regularization

In [108]:
features_cat = ['loan_purpose_name', 'applicant_sex_name', 'loan_type_name', 'loan_purpose_name', 'denial_reason_name_3','denial_reason_name_2','denial_reason_name_1']
features_num = ['loan_amount_000s', 'applicant_income_000s']
X, y = preprocessing_data_X_y(new_df_loan_approved, features_cat, features_num)

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_TEMP, y_train, y_TEMP = train_test_split(X, y, test_size=0.30) # split out into training 70% of our data
X_validation, X_test, y_validation, y_test = train_test_split(X_TEMP, y_TEMP, test_size=0.50) # split out into validation 15% of our data and test 15% of our data
print(X_train.shape, X_validation.shape, X_test.shape) # print data shape to check the sizing is correct

(258496, 46) (55392, 46) (55393, 46)

In [119]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear', penalty='l1', C=1.0).fit(X_train, y_train)
y_pred_validation = model.predict(X_validation) # next get the model's predictions for a sample in the validation set
metrics(y_validation, y_pred_validation) # finally evaluate performance
y_pred_test = model.predict(X_test) # next get the model's predictions for a sample in the validation set
metrics(y_test, y_pred_test) # finally evaluate performance

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Confusion matrix:
 [[27101   480]
 [ 2189 25622]]

Report:
               precision    recall  f1-score   support

           0       0.93      0.98      0.95     27581
           1       0.98      0.92      0.95     27811

    accuracy                           0.95     55392
   macro avg       0.95      0.95      0.95     55392
weighted avg       0.95      0.95      0.95     55392

Confusion matrix:
 [[27150   545]
 [ 2089 25609]]

Report:
               precision    recall  f1-score   support

           0       0.93      0.98      0.95     27695
           1       0.98      0.92      0.95     27698

    accuracy                           0.95     55393
   macro avg       0.95      0.95      0.95     55393
weighted avg       0.95      0.95      0.95     55393

**Conclusion** : Changing the solver we see a slight change in the confusion matrix, it has imporoved performance.

### Approach 3 : Using Random Forest

In [120]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42).fit(X_train, y_train)
y_pred_validation = model.predict(X_validation) # next get the model's predictions for a sample in the validation set
metrics(y_validation, y_pred_validation) # finally evaluate performance
y_pred_test = model.predict(X_test) # next get the model's predictions for a sample in the validation set
metrics(y_test, y_pred_test) # finally evaluate performance

Confusion matrix:
 [[27374   207]
 [ 4588 23223]]

Report:
               precision    recall  f1-score   support

           0       0.86      0.99      0.92     27581
           1       0.99      0.84      0.91     27811

    accuracy                           0.91     55392
   macro avg       0.92      0.91      0.91     55392
weighted avg       0.92      0.91      0.91     55392

Confusion matrix:
 [[27461   234]
 [ 4542 23156]]

Report:
               precision    recall  f1-score   support

           0       0.86      0.99      0.92     27695
           1       0.99      0.84      0.91     27698

    accuracy                           0.91     55393
   macro avg       0.92      0.91      0.91     55393
weighted avg       0.92      0.91      0.91     55393

**Conclusion** Approach 3 performs worse, best approach has been approach 2